### ISSUE TITLE
After executing the component

### ISSUE THREAD

**Issue by EdwinJDiaz** [aaronisme/rn-recaptcha#1]
Hello, after executing the component I am receiving the following error:

jest-haste-map: @providesModule naming collision:
Duplicate module name: ReactNativeRenderer-prod
Paths: ReactNativeProjects/project/nameproject/node_modules/rn-recaptcha/node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-prod.js collides with ReactNativeProjects/project/nameproject/node_modules/react-native/Libraries/Renderer/ReactNativeRenderer-prod.js

This warning is caused by a @providesModule declaration with the same name across two different files.
jest-haste-map: @providesModule naming collision:
Duplicate module name: ReactNativeRenderer-dev
Paths: ReactNativeProjects/project/nameproject/node_modules/rn-recaptcha/node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js collides with ReactNativeProjects/project/nameproject/node_modules/react-native/Libraries/Renderer/ReactNativeRenderer-dev.js

This warning is caused by a @providesModule declaration with the same name across two different files.
jest-haste-map: @providesModule naming collision:
Duplicate module name: ReactFabric-prod
Paths: ReactNativeProjects/project/nameproject/node_modules/rn-recaptcha/node_modules/react-native/Libraries/Renderer/oss/ReactFabric-prod.js collides with ReactNativeProjects/project/nameproject/node_modules/react-native/Libraries/Renderer/ReactFabric-prod.js

This warning is caused by a @providesModule declaration with the same name across two different files.
jest-haste-map: @providesModule naming collision:
Duplicate module name: ReactFabric-dev
Paths: ReactNativeProjects/project/nameproject/node_modules/rn-recaptcha/node_modules/react-native/Libraries/Renderer/oss/ReactFabric-dev.js collides with ReactNativeProjects/project/nameproject/node_modules/react-native/Libraries/Renderer/ReactFabric-dev.js

This warning is caused by a @providesModule declaration with the same name across two different files.
jest-haste-map: @providesModule naming collision:
Duplicate module name: react-animated
Paths: ReactNativeProjects/project/nameproject/node_modules/rn-recaptcha/node_modules/react-native/Libraries/Animated/release/package.json collides with ReactNativeProjects/project/nameproject/node_modules/react-native/Libraries/Animated/release/package.json

This warning is caused by a @providesModule declaration with the same name across two different files.
jest-haste-map: @providesModule naming collision:
Duplicate module name: Sample
Paths: ReactNativeProjects/project/nameproject/node_modules/rn-recaptcha/node_modules/react-native/Libraries/Sample/package.json collides with ReactNativeProjects/project/nameproject/node_modules/react-native/Libraries/Sample/package.json

This warning is caused by a @providesModule declaration with the same name across two different files.
jest-haste-map: @providesModule naming collision:
Duplicate module name: react-native
Paths: ReactNativeProjects/project/nameproject/node_modules/rn-recaptcha/node_modules/react-native/package.json collides with ReactNativeProjects/project/nameproject/node_modules/react-native/package.json

This warning is caused by a @providesModule declaration with the same name across two different files.
jest-haste-map: @providesModule naming collision:
Duplicate module name: react-native
Paths: ReactNativeProjects/project/nameproject/node_modules/rn-recaptcha/node_modules/react-native/package.json collides with ReactNativeProjects/project/nameproject/node_modules/react-native/package.json

This warning is caused by a @providesModule declaration with the same name across two different files.
error: bundling failed: ambiguous resolution: module `

"react-native": "0.55.0",

Thanks for your help

**Comment by aaronisme** [comment]
seems you have two version react native installed which have introduced the naming collision

**Comment by aaronisme** [comment]
move the react and react-native as devDependencies @EdwinJDiaz please install the latest package
